version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: logineko_postgres
    environment:
      POSTGRES_DB: logineko_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create-db.sh:/docker-entrypoint-initdb.d/create-db.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: logineko_keycloak
    command: start-dev --db=postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: postgres-db
      KC_DB_URL_DATABASE: logineko_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true

      # Thêm timeout cho DB connection
      KC_DB_URL_PROPERTIES: "?connectTimeout=30000&socketTimeout=30000"
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data: