services:
  postgres:
    image: postgres:15
    container_name: logineko_postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logineko_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: keycloak/keycloak:25.0.6
    container_name: logineko_keycloak
    depends_on:
      postgres:
        condition: service_healthy
    command: start --optimized
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: auth.logineko.edu.vn
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - logineko_network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: logineko_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    networks:
      - logineko_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: logineko_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    networks:
      - logineko_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: logineko_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiNTk2Y2Q4ZjM1M2ZhMmE3MDgwOTgxMzg4NzU3NWNmYWQiLCJ0IjoiNDRiOTM3NDUtYTBjNi00MTIyLWE3ZmMtZGQ2MjMzMTE5ZGYwIiwicyI6Iit6Z1NJSEEvcFhZUEtjNVc2OVlWVWgrOUdGMyt3TFdrS2dCdndEdjZoUXM9In0=
    networks:
      - logineko_network

  logineko-be:
    image: alfred0324/logineko-be:latest
    container_name: logineko_be
    depends_on:
      - keycloak
      - kafka
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: always
    networks:
      - logineko_network

volumes:
  postgres_data:
    driver: local

networks:
  logineko_network:
    driver: bridge