version: '3.8'

services:

  keycloak:
    image: keycloak/keycloak:25.0.6
    container_name: logineko_keycloak
    # Use a custom entrypoint to build first, then start
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        /opt/keycloak/bin/kc.sh build --features=token-exchange,preview
        /opt/keycloak/bin/kc.sh start --optimized

    environment:
      # Admin account
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Database config
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ep-royal-sky-a1wya79r-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
      KC_DB_USERNAME: neondb_owner
      KC_DB_PASSWORD: npg_BqSeuK9wp1iR

      # Hostname config
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
#      KC_PROXY: edge

      # Connection pool settings
      KC_DB_POOL_INITIAL_SIZE: 10
      KC_DB_POOL_MIN_SIZE: 5
      KC_DB_POOL_MAX_SIZE: 20
      KC_DB_POOL_MAX_LIFETIME: 600000

      # Performance optimizations
      KC_CACHE: ispn
      KC_CACHE_STACK: tcp

      # Session and token optimizations
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_SUCCESS_LEVEL: info
      KC_SPI_EVENTS_LISTENER_JBOSS_LOGGING_ERROR_LEVEL: warn

    ports:
      - "8080:8080"
    restart: unless-stopped
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: logineko_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: logineko_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  logineko-be:
    image: alfred0324/logineko-be:latest
    container_name: logineko_be
    depends_on:
      - keycloak
      - kafka
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: always
volumes:
  postgres-data: